

  // darkMode: 'class', // Enables dark mode using a class
  // theme: {
  //   extend: {
  //     colors: {
  //       // Light Mode Colors
  //       neutral: {
  //         'base-default': '#F7F8FA',
  //         'base-default-alt': '#EFF0F5',
  //         'base-subtle': '#E0E2E8',
  //         'base-subtle-alt': '#D7D9DF',
  //         'base-highlight': '#C5C8CE',
  //         'base-highlight-alt': '#B2B5BB',
  //         'base-inverted': '#1A1B1D',
  //         'base-weak': '#A7A9B2',
  //         'base-main': '#868993',
  //         'base-strong': '#656871',
  //         'base-divider': '#4D5055',
  //         'base-disabled': '#CCCCCC',
  //         'base-selection': '#E3F2FD',
  //         'base-overlay': '#F4F6F8',
  //         'base-solid': '#FFFFFF',
  //         'base-solid-alt': '#F0F0F0',
  //         'base-divider-on-solid': '#E5E7EB',
  //         'base-disabled-on-solid': '#D1D5DB',
  //       },
  //       brand: {
  //         'subtle': '#E3F2FD',
  //         'highlight': '#BBDEFB',
  //         'weak': '#90CAF9',
  //         'main': '#42A5F5',
  //         'strong': '#1E88E5',
  //       },
  //       success: {
  //         'subtle': '#E8F5E9',
  //         'highlight': '#C8E6C9',
  //         'weak': '#A5D6A7',
  //         'main': '#66BB6A',
  //         'strong': '#388E3C',
  //       },
  //       warning: {
  //         'subtle': '#FFF8E1',
  //         'highlight': '#FFECB3',
  //         'weak': '#FFD54F',
  //         'main': '#FFB74D',
  //         'strong': '#FFA726',
  //       },
  //       error: {
  //         'subtle': '#FFEBEE',
  //         'highlight': '#FFCDD2',
  //         'weak': '#E57373',
  //         'main': '#F44336',
  //         'strong': '#D32F2F',
  //       },

  //       // Dark Mode Colors
  //       'dark-neutral': {
  //         'base-default': '#121212',
  //         'base-default-alt': '#181818',
  //         'base-subtle': '#1F1F1F',
  //         'base-subtle-alt': '#232323',
  //         'base-highlight': '#2E2E2E',
  //         'base-highlight-alt': '#383838',
  //         'base-inverted': '#FFFFFF',
  //         'base-weak': '#424242',
  //         'base-main': '#535353',
  //         'base-strong': '#646464',
  //         'base-divider': '#757575',
  //         'base-disabled': '#9E9E9E',
  //         'base-selection': '#1E88E5',
  //         'base-overlay': '#303030',
  //         'base-solid': '#212121',
  //         'base-solid-alt': '#2A2A2A',
  //         'base-divider-on-solid': '#373737',
  //         'base-disabled-on-solid': '#5C5C5C',
  //       },
  //       'dark-brand': {
  //         'subtle': '#264D73',
  //         'highlight': '#356BA3',
  //         'weak': '#4C89D0',
  //         'main': '#5B9DF5',
  //         'strong': '#388CFB',
  //       },
  //       'dark-success': {
  //         'subtle': '#276738',
  //         'highlight': '#3D9252',
  //         'weak': '#48AF58',
  //         'main': '#64D17C',
  //         'strong': '#4CAF50',
  //       },
  //       'dark-warning': {
  //         'subtle': '#7D5000',
  //         'highlight': '#AE7A14',
  //         'weak': '#E08C15',
  //         'main': '#FFA726',
  //         'strong': '#FFB74D',
  //       },
  //       'dark-error': {
  //         'subtle': '#B43A3A',
  //         'highlight': '#E04747',
  //         'weak': '#F74A4A',
  //         'main': '#FF5252',
  //         'strong': '#EF5350',
  //       },
  //     },
  //     borderColor: {
  //       'border-neutral-base-subtle': '#E0E0E0',
  //       'border-neutral-base-subtle-alt': '#D3D3D3',
  //       'border-neutral-base-highlight': '#CCCCCC',
  //       'border-neutral-base-weak': '#B3B3B3',
  //       'border-neutral-base-main': '#9E9E9E',
  //       'border-neutral-base-strong': '#707070',
  //       'border-neutral-base-divider': '#F5F5F5',
  //       'border-neutral-base-disabled': '#D8D8D8',
  //       'border-neutral-base-subtle-on-solid': '#E5E5E5',
  //       'border-neutral-base-highlight-on-solid': '#CFCFCF',
  //       'border-neutral-base-divider-on-solid': '#EFEFEF',
  //       'border-neutral-base-disabled-on-solid': '#EAEAEA',

  //       // Brand Border Colors (Light Mode)
  //       'border-brand-subtle': '#DCEFFD',
  //       'border-brand-highlight': '#A3D4FA',
  //       'border-brand-weak': '#67B4F7',
  //       'border-brand-main': '#1E90FF',
  //       'border-brand-strong': '#0074CC',
  //       'border-brand-subtle-on-solid': '#D0E4F9',
  //       'border-brand-highlight-on-solid': '#ADD5F3',

  //       // Success Border Colors (Light Mode)
  //       'border-success-subtle': '#DFF5E4',
  //       'border-success-highlight': '#ADEBBF',
  //       'border-success-main': '#4CAF50',
  //       'border-success-strong': '#388E3C',

  //       // Warning Border Colors (Light Mode)
  //       'border-warning-subtle': '#FFF4DB',
  //       'border-warning-highlight': '#FFE6B3',
  //       'border-warning-main': '#FF9800',
  //       'border-warning-strong': '#F57C00',


  //       // Error Border Colors (Light Mode)
  //       'border-error-subtle': '#FDECEA',
  //       'border-error-highlight': '#F8C1B8',
  //       'border-error-main': '#F44336',
  //       'border-error-strong': '#D32F2F',

  //       // Dark Mode Border Colors
  //       'border-base-subtle': '#303030',
  //       'border-base-strong': '#5C5C5C',
  //       'border-brand-main': '#5B9DF5',
  //       'border-success-main': '#64D17C',
  //       'border-warning-main': '#FFA726',
  //       'border-error-main': '#FF5252',
  //     },
  //     textColor: {
  //       'base-stronger': '#212121',
  //       'base-strong': '#424242',
  //       'base-main': '#616161',
  //       'base-weak': '#757575',
  //       'brand-main': '#42A5F5',
  //       'success-main': '#66BB6A',
  //       'warning-main': '#FFA726',
  //       'error-main': '#F44336',
  //       // Dark Mode Text Colors
  //       'text-base-stronger': '#FFFFFF',
  //       'text-base-main': '#CCCCCC',
  //       'text-brand-main': '#42A5F5',
  //       'text-success-main': '#66BB6A',
  //       'text-warning-main': '#FFA726',
  //       'text-error-main': '#F74A4A',
  //     },
  //     foregroundColor: {
  //       'base-stronger': '#212121',
  //       'base-main': '#616161',
  //       'brand-main': '#42A5F5',
  //       'success-main': '#66BB6A',
  //       'warning-main': '#FFA726',
  //       'error-main': '#F44336',
  //       // Dark Mode Foreground Colors
  //       'fg-base-stronger': '#FFFFFF',
  //       'fg-base-main': '#CCCCCC',
  //       'fg-brand-main': '#5B9DF5',
  //       'fg-success-main': '#64D17C',
  //       'fg-warning-main': '#FFA726',
  //       'fg-error-main': '#FF5252',
  //     },
  //     linkColor: {
  //       'base-default': '#616161',
  //       'brand-default': '#42A5F5',
  //       'success-default': '#66BB6A',
  //       'warning-default': '#FFA726',
  //       'error-default': '#F44336',
  //       // Dark Mode Link Colors
  //       'link-base-default': '#FFFFFF',
  //       'link-brand-default': '#42A5F5',
  //       'link-success-default': '#66BB6A',
  //       'link-warning-default': '#FFA726',
  //       'link-error-default': '#EF5350',
  //     },
  //   },
  // },
  // variants: {
  //   extend: {
  //     backgroundColor: ['dark'],
  //     textColor: ['dark'],
  //     borderColor: ['dark'],
  //     linkColor: ['dark'],
  //   },
  // },
  // plugins: [],